apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "55"
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAmkij5IwsyS+TK9LsNktO+UH8WugopaICLk0PjQWcMKgMIgQCEIgEcQDVm4lyCxCj14r9HcsBCIfIQcuxWFC9+6DXVa6pKbw3Ey6lYKtG1OMEXHdp2lhLHR08YjKwXdfEIvfo1tYwx7AikbOeSaFtXXnSx2B6FYdxHH3Sw+ftTZNSOe07CFPwtt4EmsIm3XZGcmCLiOhwpgD99IyEoEpu0QCIwym+ImR/wPY/Ge8ZE/pSBvYJZ61fnUr/tqJGMjOwRaTCJVP+isbt0cnjoW7MZRC4bwPVdQDhER5l0QrwJvHr9sltDLcZW21Un50P5/of90gc+cB7QDRyfG0Sn09XARG0cHqSSogPFlJ1Z2agdi8ySxNO66/dW+dAwFOlTqko1BTPYvd29Gx4S/Wt5QJ1pbBhB9Nyk0y59HxaWtUah03aygzCSpHWVRLeF3IVP/rLAjmx8AP4KdeBewcOqp8gBs/IroGab2BDMnaRu2snIPpzlIpWDV8B/fDr2pXrJ68u7hRVPhNT/XKvrTs9SaW8XTG8MEfaBHZcVYRpofwVKecTZbv9ur3NFsEEsMN8qWczIJjbr0zxbWnl0ueFmjRzwutkX5h9VAZbohbJjUqHtlhKG91mAyQwwKqGdgIJkRvGkE6PtZuNHjhd/MVsLtzhm6qMot65oBd+JL0eQZrqs09HlPpInxMIgWmIoSlRQ8hU=
    admin-user: AgCqyHO98a6kNx4XypTxwaJ+pjDY7HaVU/4BPh8vcpceS6mGJuveqL68XIB6Yx3qZiRZg+X0nkfUGvH9s/2eusZsbdwohh/AsszWOBXkdy7kyAflfrZleaLow48UrlDi1R6YPwUaJF8WgFY0+9TY/Ql6LB+QZlN/DvPBwaOV4K6Xl8biIjlQsBDokvulvsaP1ETIXZkPXQwNclRSiIRhvkYq6P/6u1A1fAtQKFU2HgwP459UOa6JeK5rfaL5vkxu0GCxnj8L54c0sK7+57ThCe1kDd7O0RufM7eK9lDh3P8QYZbGn+E3mu9YEq976BKl8fIuPqLtlEGl9yWF2Rew94be9GNhxM8E0AwRXtRStdOYad+MqG8rawWhLXmnuSOV4+NNN2sAbmjBvh0A99A5yVEpNLSNCnjdTWeic+7jmpVZ/qCPuMHIMnmGNd4J0c02sBQgM37MqnOFFWQOIdGfKzBi/7FruDTv/sMPR+MwOZMmX3qKEA7Ho9feZnwcUGdq5TGOj/ezMRRNYelZcQe9IQtVAY/W48C+Ti9OP84jdAOW+QKp1zSW7mhmmD3UN+OcLBf5dRsMSXsvtv1H8YsWY2K/PMnVIWEDHBPX6AfcRN1ieWljWYlCKGg7FEgy+YvsQT8GO083DpCAvXcSFqaYRwRs14anuiDxaz3XyCmEX+JrKd64f0xxWMlRt2wO+g+s63mUqtDn3A==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
