apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "55"
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAFvLbIfUg6qJNr9XE3EEI3G8TZ3VNkP9ziSVqsPmWJL/lNYIinCHJtTs85dWN0od/qfHGjrsuicJNwlxg9RItEgrTOISNrZlYcwwi57EvwyLY8HYm2DhkV0OyeU2t96Jnr+XfYcuGavE+f/Wl745d7DdOU7ihyT8gYaunhwGABFTbHsXJMpA+upSzuuj960sqaKjhLjPIU9/7t9qXMEFmZeXxdBQKdM6SfZYF5f2+cfICroX8+qJ4nA7AQCACry2c9ZynPwODHiCe50Qden/cPB/l0exhNwyQMGX6zIPWCBMWQz60Ix630S/BXiBssNutuvO63TOKP0YJcJelhcbdY64u8H5qYc9enr0/PJSmVeMasorn7kKm7sMC/ms7ZcNhdC7choHc6SngnaUKB8NGZto84dd73q9UVzGqS0AbrjIMEATNzht2dVtNhtPEMGWnzVn5L/5jt5T+nnTW7aswP08ON+UnFZeZd7xsJsv9az7suMxC8ZP72+djlw51edySxp0JZUJItNBdJF9jkD2I8/u7qd7ett4bZFax9EKuIwrz6feya+9MJjVyUpHIt1TyhjWMnqa42Xej7lLQRu7WTrRz4UtoU+Umrq3sPU9AVWqRjiS2Qbg4onBDD509fRskbZ1zAt0rH7UU4C7DTanVMXRb4+4s3/3vtInRqHcudbNJk3VBF5BZcJBZAi1qF1gBSAKv7cCexBCIBXw==
    admin-user: AgBaiS+wYpHGzs2ALfUh+2p8ofsaF5VueDasUcCZewUk5UkLuF0ktMeWPcFxd3EXaMamcktZqSC77h4cYBDp3yPjD+QTL83vLG8nP6eH1byx5jlw/rZbPvXoDPneCKl/Gs1weyLOrlNFHLwohsYI2QgZvG8wK+nk72dMErnJaCjF2NI616Bfki/g6BZcRvsCPsWjybXS5SMFcX+Y9Vr2IFY02ScCM5Qj41h6R69YbkHDTlSoUgYcO9UhNKbfHcXw/5akex7r9v8UuJV0Pu1NmJueNvdJ/Uf8Zrd12NIRNbLeD6k5evME1OiPggrXOV0zh/Lw7PGeu0TPzdflQ4JKIoZ0RvFwkI1vfX7M60EALXfhjto2cjeEpVGQP6x2YG62m9zajzG3QiMs6WTfnZMyjO9xXudnpS5tIhl2mmtzvC3FWkbTmbn/qG37t+2dUPhFnlN/8FTFgDQyg/kOhn2M/VV836L2H7s3nDfhrlRk7wloqtXjQd0VII1d2REo5OAFvtK2FTHlBjjfuBVBmlCNf+82DmDMJQFsffvCGAZ1RTuTdG10tKhlhMThTptfGq+mJxfcTpGRdp8sVjdjZIXi+D3O1kWuumxVyP8bHM/Kf86niZAj2Zne69q+tZMOlROsZXZXFUm2TKiSwG7oUY1Mj91Y6v+74Wut+/C5+GP5PVGdooYC2L3aIvHpcfyAI6NvItRTE5CQ6A==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
