apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "41"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: promtail
    targetRevision: 6.17.1
    helm:
      releaseName: promtail
      values: |
        daemonset:
          enabled: true
        deployment:
          enabled: false
        image:
          tag: "3.6.11"
        config:
          clients:
            - url: http://loki.logging.svc.cluster.local:3100/loki/api/v1/push
          snippets:
            pipelineStages:
              - cri: {}
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        serviceMonitor:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
